spring.application.name=demo
# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ddl-auto (updates database schema based on entities)
# Use 'update' for development. Use 'validate' or 'none' for production.
spring.jpa.hibernate.ddl-auto=update

# Show and format the generated SQL in the console for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true